[package]
name = "cogvlm_image_preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
ndarray = "0.15"
rayon = "1.8"
rand = "0.8"
ndarray-stats = "0.4"
wide = "0.7"
ndarray-rand = "0.14"
rand_distr = "0.4"
ndarray-npy = "0.8"
